server:
    #端口
    port: 8080
    session:
        #session过期期限
        timeout: 1000 # in seconds
    context-path: /SPRINGBOOT-ACTIVEMQ
    
spring:
    application:
        name: SPRINGBOOT-ACTIVEMQ
    #db  -- 默认数据源
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mc_test?characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    activemq:
        broker-url: tcp://localhost:61616  
        in-memory: true  
        pool:
            enabled: false
            
#日志管理            
logging: 
    level: 
        zqit: debug
            
    
